# Generated by Django 5.1.15 on 2026-09-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='茶园名称')),
                ('altitudeBand', models.CharField(max_length=60, verbose_name='海拔带')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '茶园',
                'verbose_name_plural': '茶园',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troughCode', models.CharField(max_length=40, verbose_name='槽位编号')),
                ('cultivar', models.CharField(max_length=80, verbose_name='茶树品种')),
                ('loadKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='装叶量(kg)')),
                ('status', models.CharField(choices=[('loading', '装叶中'), ('withering', '萎凋中'), ('ready', '可下槽')], default='loading', max_length=20, verbose_name='状态')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troughs', to='gardens.garden', verbose_name='茶园')),
            ],
            options={
                'verbose_name': '萎凋槽',
                'verbose_name_plural': '萎凋槽',
                'ordering': ['garden__name', 'troughCode'],
            },
        ),
        migrations.CreateModel(
            name='WitherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateTimeField(verbose_name='开始时间')),
                ('targetMoisture', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='目标含水率(%)')),
                ('actualMoisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='实测含水率(%)')),
                ('rollGrade', models.CharField(max_length=40, verbose_name='揉捻等级')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='gardens.trough', verbose_name='萎凋槽')),
            ],
            options={
                'verbose_name': '萎凋批次',
                'verbose_name_plural': '萎凋批次',
                'ordering': ['-startedAt', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trough',
            constraint=models.UniqueConstraint(fields=('garden', 'troughCode'), name='uniq_trough_code_per_garden'),
        ),
    ]
